-- Add UUID v7 column to all entity tables.
-- Existing rows get gen_random_uuid() as a placeholder.
-- New rows receive a time-ordered UUID v7 generated by the application via @PrePersist.

ALTER TABLE departments                  ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE department_stakeholders      ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE integration_settings         ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE observations                 ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE observation_messages         ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE observation_closure_requests ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE policies                     ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE policy_approval_cycles       ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE policy_approval_steps        ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE policy_versions              ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE policy_version_files         ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE policy_step_messages         ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE reported_items               ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE reported_item_messages       ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE roles                        ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE users                        ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;
ALTER TABLE audit_log                    ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE;

ALTER TABLE departments                  ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE department_stakeholders      ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE integration_settings         ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE observations                 ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE observation_messages         ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE observation_closure_requests ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE policies                     ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE policy_approval_cycles       ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE policy_approval_steps        ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE policy_versions              ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE policy_version_files         ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE policy_step_messages         ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE reported_items               ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE reported_item_messages       ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE roles                        ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE users                        ALTER COLUMN uuid DROP DEFAULT;
ALTER TABLE audit_log                    ALTER COLUMN uuid DROP DEFAULT;
