CREATE TABLE decision_registers (
    id                      BIGSERIAL PRIMARY KEY,
    decision_number         VARCHAR(50)  NOT NULL UNIQUE,
    title                   VARCHAR(300) NOT NULL,
    decision_date           DATE         NOT NULL,
    decision_maker          VARCHAR(200) NOT NULL,
    related_risk            VARCHAR(200),
    related_policy_control  VARCHAR(300),
    background_context      TEXT,
    alternatives_considered TEXT,
    decision_outcome        TEXT,
    justification           TEXT,
    impact_assessment       TEXT,
    actions_required        TEXT,
    owner                   VARCHAR(200),
    due_date                DATE,
    review_date             DATE,
    status                  VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    attachment_path         VARCHAR(500),
    attachment_name         VARCHAR(255),
    uuid                    UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    created_at              TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP    NOT NULL DEFAULT now(),
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64)
);
